### ISSUE TITLE
Возвращаемое значение в действии 'Получить значение'

### ISSUE THREAD

**Issue by CheshireCaat** [CheshireCaat/JSONModule#1]
Определиться, что нужно возвращать, если указан пустой путь для парсинга - значение первого ключа объекта, весь объект целиком, undefined или ошибку?

UPD: можно ещё запретить ставить пустой путь для действий получения одного ключа или одного значения.

**Comment by bablosoft** [comment]
При возникновении любой ошибки нужно возвращать пустую строку.
